version: '3.1'

services:
  opencart:
      build:
        dockerfile: opencart/Dockerfile
      restart: always
      ports:
        - 8080:8080
      environment:
        ALLOW_EMPTY_PASSWORD: yes
        OPENCART_DATABASE_HOST: db
        OPENCART_DATABASE_USER: exampleuser
        OPENCART_DATABASE_PASSWORD: examplepass
        OPENCART_DATABASE_NAME: exampledb
        OPENCART_HOST: localhost:8080
        XHGUI_ENABLE: 1
        XHGUI_URL: http://xhgui
      volumes:
        # From volume
        - opencart:/bitnami/opencart
        # From host
        - ./opencart/xhgui:/opt/bitnami/xhgui
        - ./opencart/composer:/opt/bitnami/composer
        - ./opencart/source/index.php:/opt/bitnami/opencart/index.php
  xhgui:
    image: xhgui/xhgui
    ports:
      - 8081:80
    volumes:
      - ./xhgui/nginx.conf:/etc/nginx/http.d/default.conf:ro
      - ./xhgui/config.default.php:/var/www/xhgui/config/config.default.php
    environment:
      - XHGUI_MONGO_HOSTNAME=mongo
      - XHGUI_MONGO_DATABASE=xhprof

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  mongo:
    image: percona/percona-server-mongodb:3.6
    # (case sensitive) engine: mmapv1, rocksdb, wiredTiger, inMemory
    command: --storageEngine=wiredTiger
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=xhprof

volumes:
  opencart:
  db:
